site_name: Strikt
site_url: https://strikt.io/
repo_name: 'robfletcher/strikt'
repo_url: https://github.com/robfletcher/strikt
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'indigo'
    accent: 'orange'
  logo:
    icon: 'check_circle'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false
pages:
  - Home: index.md
  - Getting Started: user-guide/getting-started.md
  - Assertion Styles: user-guide/assertion-styles.md
  - Strongly-Typed Assertions: user-guide/flow-typing.md
  - Mapping Over Assertion Subjects: user-guide/mapping.md
  - Common Assertion Patterns: user-guide/common-patterns.md
  - Custom Assertions: user-guide/custom-assertions.md
  - About: about.md
#  - API: api/strikt/index.md
markdown_extensions:
  - admonition
site_description: An assertion library for Kotlin
site_author: Rob Fletcher
site_dir: build/site
