defaults: &defaults
  docker:
    - image: circleci/openjdk:10-jdk
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: ./gradlew build
      - run:
          name: Archive test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  build-java6:
    <<: *defaults
    docker:
      - image: circleci/openjdk:6-jdk
    steps:
      - checkout
      - run: ./gradlew build
      - run:
          name: Archive test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  release:
    <<: *defaults
    steps:
      - checkout
      - run: ./gradlew -Prelease.useLastTag=true final

  site:
    <<: *defaults
    steps:
      - checkout
      - run: ./gradlew publishGhPages

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
      - build-java6:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - site:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
